/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendingRouteImport } from './routes/trending'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuestsRouteImport } from './routes/quests'
import { Route as QuestSubmitRouteImport } from './routes/quest-submit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MasterclassesRouteImport } from './routes/masterclasses'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as FeedCreateRouteImport } from './routes/feed.create'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminQuestReviewsRouteImport } from './routes/admin.quest-reviews'
import { Route as ApiGoogleStatusRouteImport } from './routes/api/google/status'
import { Route as ApiGoogleConnectRouteImport } from './routes/api/google/connect'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiPublicIcsTokenRouteImport } from './routes/api/public/ics/$token'

const TrendingRoute = TrendingRouteImport.update({
  id: '/trending',
  path: '/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestsRoute = QuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => rootRouteImport,
} as any)
const QuestSubmitRoute = QuestSubmitRouteImport.update({
  id: '/quest-submit',
  path: '/quest-submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterclassesRoute = MasterclassesRouteImport.update({
  id: '/masterclasses',
  path: '/masterclasses',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedCreateRoute = FeedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => FeedRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestReviewsRoute = AdminQuestReviewsRouteImport.update({
  id: '/quest-reviews',
  path: '/quest-reviews',
  getParentRoute: () => AdminRoute,
} as any)
const ApiGoogleStatusRoute = ApiGoogleStatusRouteImport.update({
  id: '/api/google/status',
  path: '/api/google/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleConnectRoute = ApiGoogleConnectRouteImport.update({
  id: '/api/google/connect',
  path: '/api/google/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIcsTokenRoute = ApiPublicIcsTokenRouteImport.update({
  id: '/api/public/ics/$token',
  path: '/api/public/ics/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRouteWithChildren
  '/capabilities': typeof CapabilitiesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRouteWithChildren
  '/masterclasses': typeof MasterclassesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/quest-submit': typeof QuestSubmitRoute
  '/quests': typeof QuestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/support': typeof SupportRoute
  '/trending': typeof TrendingRoute
  '/admin/quest-reviews': typeof AdminQuestReviewsRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/feed/create': typeof FeedCreateRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/google/status': typeof ApiGoogleStatusRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRouteWithChildren
  '/capabilities': typeof CapabilitiesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRouteWithChildren
  '/masterclasses': typeof MasterclassesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/quest-submit': typeof QuestSubmitRoute
  '/quests': typeof QuestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/support': typeof SupportRoute
  '/trending': typeof TrendingRoute
  '/admin/quest-reviews': typeof AdminQuestReviewsRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/feed/create': typeof FeedCreateRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/google/status': typeof ApiGoogleStatusRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/admin': typeof AdminRouteWithChildren
  '/agent': typeof AgentRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRouteWithChildren
  '/capabilities': typeof CapabilitiesRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/feed': typeof FeedRouteWithChildren
  '/masterclasses': typeof MasterclassesRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/opportunities': typeof OpportunitiesRoute
  '/profile': typeof ProfileRoute
  '/quest-submit': typeof QuestSubmitRoute
  '/quests': typeof QuestsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/support': typeof SupportRoute
  '/trending': typeof TrendingRoute
  '/admin/quest-reviews': typeof AdminQuestReviewsRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/feed/create': typeof FeedCreateRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/google/connect': typeof ApiGoogleConnectRoute
  '/api/google/status': typeof ApiGoogleStatusRoute
  '/api/public/ics/$token': typeof ApiPublicIcsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/admin'
    | '/agent'
    | '/assistant'
    | '/auth'
    | '/capabilities'
    | '/community'
    | '/dashboard'
    | '/feed'
    | '/masterclasses'
    | '/notifications'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/quest-submit'
    | '/quests'
    | '/reset-password'
    | '/schedule'
    | '/support'
    | '/trending'
    | '/admin/quest-reviews'
    | '/api/chat'
    | '/auth/callback'
    | '/feed/create'
    | '/projects/$id'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/google/status'
    | '/api/public/ics/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/admin'
    | '/agent'
    | '/assistant'
    | '/auth'
    | '/capabilities'
    | '/community'
    | '/dashboard'
    | '/feed'
    | '/masterclasses'
    | '/notifications'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/quest-submit'
    | '/quests'
    | '/reset-password'
    | '/schedule'
    | '/support'
    | '/trending'
    | '/admin/quest-reviews'
    | '/api/chat'
    | '/auth/callback'
    | '/feed/create'
    | '/projects/$id'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/google/status'
    | '/api/public/ics/$token'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/admin'
    | '/agent'
    | '/assistant'
    | '/auth'
    | '/capabilities'
    | '/community'
    | '/dashboard'
    | '/feed'
    | '/masterclasses'
    | '/notifications'
    | '/onboarding'
    | '/opportunities'
    | '/profile'
    | '/quest-submit'
    | '/quests'
    | '/reset-password'
    | '/schedule'
    | '/support'
    | '/trending'
    | '/admin/quest-reviews'
    | '/api/chat'
    | '/auth/callback'
    | '/feed/create'
    | '/projects/$id'
    | '/api/google/callback'
    | '/api/google/connect'
    | '/api/google/status'
    | '/api/public/ics/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgentRoute: typeof AgentRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRouteWithChildren
  CapabilitiesRoute: typeof CapabilitiesRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  FeedRoute: typeof FeedRouteWithChildren
  MasterclassesRoute: typeof MasterclassesRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  ProfileRoute: typeof ProfileRoute
  QuestSubmitRoute: typeof QuestSubmitRoute
  QuestsRoute: typeof QuestsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  SupportRoute: typeof SupportRoute
  TrendingRoute: typeof TrendingRoute
  ApiChatRoute: typeof ApiChatRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiGoogleConnectRoute: typeof ApiGoogleConnectRoute
  ApiGoogleStatusRoute: typeof ApiGoogleStatusRoute
  ApiPublicIcsTokenRoute: typeof ApiPublicIcsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trending': {
      id: '/trending'
      path: '/trending'
      fullPath: '/trending'
      preLoaderRoute: typeof TrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quests': {
      id: '/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof QuestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quest-submit': {
      id: '/quest-submit'
      path: '/quest-submit'
      fullPath: '/quest-submit'
      preLoaderRoute: typeof QuestSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterclasses': {
      id: '/masterclasses'
      path: '/masterclasses'
      fullPath: '/masterclasses'
      preLoaderRoute: typeof MasterclassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed/create': {
      id: '/feed/create'
      path: '/create'
      fullPath: '/feed/create'
      preLoaderRoute: typeof FeedCreateRouteImport
      parentRoute: typeof FeedRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quest-reviews': {
      id: '/admin/quest-reviews'
      path: '/quest-reviews'
      fullPath: '/admin/quest-reviews'
      preLoaderRoute: typeof AdminQuestReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/google/status': {
      id: '/api/google/status'
      path: '/api/google/status'
      fullPath: '/api/google/status'
      preLoaderRoute: typeof ApiGoogleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/connect': {
      id: '/api/google/connect'
      path: '/api/google/connect'
      fullPath: '/api/google/connect'
      preLoaderRoute: typeof ApiGoogleConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ics/$token': {
      id: '/api/public/ics/$token'
      path: '/api/public/ics/$token'
      fullPath: '/api/public/ics/$token'
      preLoaderRoute: typeof ApiPublicIcsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminQuestReviewsRoute: typeof AdminQuestReviewsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminQuestReviewsRoute: AdminQuestReviewsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface FeedRouteChildren {
  FeedCreateRoute: typeof FeedCreateRoute
}

const FeedRouteChildren: FeedRouteChildren = {
  FeedCreateRoute: FeedCreateRoute,
}

const FeedRouteWithChildren = FeedRoute._addFileChildren(FeedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AdminRoute: AdminRouteWithChildren,
  AgentRoute: AgentRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRouteWithChildren,
  CapabilitiesRoute: CapabilitiesRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  FeedRoute: FeedRouteWithChildren,
  MasterclassesRoute: MasterclassesRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  ProfileRoute: ProfileRoute,
  QuestSubmitRoute: QuestSubmitRoute,
  QuestsRoute: QuestsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  SupportRoute: SupportRoute,
  TrendingRoute: TrendingRoute,
  ApiChatRoute: ApiChatRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiGoogleConnectRoute: ApiGoogleConnectRoute,
  ApiGoogleStatusRoute: ApiGoogleStatusRoute,
  ApiPublicIcsTokenRoute: ApiPublicIcsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
